spring:
  devtools:
    restart:
      enabled: true
      poll-interval: 1s
      quiet-period: 400ms

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    endpoint: ${DB_ENDPOINT}
    key: ${DB_KEY}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        debug: true


app:
  cors:
    allowed-origins: ${FRONTEND_URL}
    allowed-methods: GET, POST, PUT, PATCH, DELETE, OPTIONS
    allowed-headers: Content-Type, Authorization
    allow-credentials: true
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 3600000 # 1 hour
    refresh-expiration-ms: 604800000 # 7 days
    cookie:
      secure: ${COOKIE_SECURE:true}
      same-site: ${COOKIE_SAME_SITE:None}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
