spring:
  devtools:
    restart:
      enabled: true
      poll-interval: 1s
      quiet-period: 400ms

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    endpoint: ${DB_ENDPOINT}
    key: ${DB_KEY}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

apilayer:
  api-key: ${EMAIL_API_KEY:}

app:
  cors:
    allowed-origins: ${FRONTEND_URL}
    allowed-methods: GET, POST, PUT, PATCH, DELETE, OPTIONS
    allowed-headers: Content-Type, Authorization
    allow-credentials: true
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 3600000 # 1 hour
    refresh-expiration-ms: 604800000 # 7 days

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
